[2024-04-09T17:00:42.450+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2024-04-09T17:00:42.494+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2024-04-09T17:00:42.497+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T17:00:42.552+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): retried_task> on 2023-09-14 00:00:00+00:00
[2024-04-09T17:00:42.596+0000] {standard_task_runner.py:60} INFO - Started process 1252 to run task
[2024-04-09T17:00:42.615+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_states_demo', 'retried_task', 'scheduled__2023-09-14T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/task_states_demo.py', '--cfg-path', '/tmp/tmpsoe4jj4g']
[2024-04-09T17:00:42.635+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask retried_task
[2024-04-09T17:00:42.829+0000] {task_command.py:423} INFO - Running <TaskInstance: task_states_demo.retried_task scheduled__2023-09-14T00:00:00+00:00 [running]> on host fe7355ff6de5
[2024-04-09T17:00:44.020+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_states_demo' AIRFLOW_CTX_TASK_ID='retried_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-14T00:00:00+00:00'
[2024-04-09T17:00:44.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T17:00:44.768+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-04-09T17:00:45.157+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T17:00:45.196+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-09T17:00:45.346+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-09T17:00:45.402+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=task_states_demo, task_id=retried_task, execution_date=20230914T000000, start_date=20240409T170042, end_date=20240409T170045
[2024-04-09T17:00:45.573+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 200 for task retried_task (Bash command failed. The command returned a non-zero exit code 1.; 1252)
[2024-04-09T17:00:45.821+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T17:00:46.232+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
