[2024-04-09T16:53:45.876+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-17T00:00:00+00:00 [queued]>
[2024-04-09T16:53:46.145+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-17T00:00:00+00:00 [queued]>
[2024-04-09T16:53:46.165+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T16:53:46.349+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): retried_task> on 2023-08-17 00:00:00+00:00
[2024-04-09T16:53:46.421+0000] {standard_task_runner.py:60} INFO - Started process 776 to run task
[2024-04-09T16:53:46.466+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_states_demo', 'retried_task', 'scheduled__2023-08-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/task_states_demo.py', '--cfg-path', '/tmp/tmpwpn58mss']
[2024-04-09T16:53:46.524+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask retried_task
[2024-04-09T16:53:47.472+0000] {task_command.py:423} INFO - Running <TaskInstance: task_states_demo.retried_task scheduled__2023-08-17T00:00:00+00:00 [running]> on host fe7355ff6de5
[2024-04-09T16:53:48.861+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_states_demo' AIRFLOW_CTX_TASK_ID='retried_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-17T00:00:00+00:00'
[2024-04-09T16:53:48.908+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T16:53:48.912+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-04-09T16:53:49.041+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T16:53:49.072+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-09T16:53:49.365+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-09T16:53:49.804+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=task_states_demo, task_id=retried_task, execution_date=20230817T000000, start_date=20240409T165345, end_date=20240409T165349
[2024-04-09T16:53:50.268+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 105 for task retried_task (Bash command failed. The command returned a non-zero exit code 1.; 776)
[2024-04-09T16:53:50.720+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T16:53:51.795+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
