[2024-04-09T16:59:38.638+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2024-04-09T16:59:38.687+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2024-04-09T16:59:38.692+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-09T16:59:38.742+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): retried_task> on 2023-08-29 00:00:00+00:00
[2024-04-09T16:59:38.753+0000] {standard_task_runner.py:60} INFO - Started process 1139 to run task
[2024-04-09T16:59:38.774+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_states_demo', 'retried_task', 'scheduled__2023-08-29T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/task_states_demo.py', '--cfg-path', '/tmp/tmpzl8ye04k']
[2024-04-09T16:59:38.797+0000] {standard_task_runner.py:88} INFO - Job 174: Subtask retried_task
[2024-04-09T16:59:38.992+0000] {task_command.py:423} INFO - Running <TaskInstance: task_states_demo.retried_task scheduled__2023-08-29T00:00:00+00:00 [running]> on host fe7355ff6de5
[2024-04-09T16:59:39.406+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_states_demo' AIRFLOW_CTX_TASK_ID='retried_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:00:00+00:00'
[2024-04-09T16:59:39.449+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T16:59:39.457+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-04-09T16:59:39.574+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T16:59:39.606+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-09T16:59:39.626+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-09T16:59:39.637+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=task_states_demo, task_id=retried_task, execution_date=20230829T000000, start_date=20240409T165938, end_date=20240409T165939
[2024-04-09T16:59:39.671+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 174 for task retried_task (Bash command failed. The command returned a non-zero exit code 1.; 1139)
[2024-04-09T16:59:39.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T16:59:40.032+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
