[2024-04-09T17:09:43.418+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-04-09T17:09:43.463+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2024-04-09T17:09:43.466+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T17:09:43.540+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): retried_task> on 2023-10-05 00:00:00+00:00
[2024-04-09T17:09:43.583+0000] {standard_task_runner.py:60} INFO - Started process 1814 to run task
[2024-04-09T17:09:43.635+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_states_demo', 'retried_task', 'scheduled__2023-10-05T00:00:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/task_states_demo.py', '--cfg-path', '/tmp/tmpkpsz6zet']
[2024-04-09T17:09:43.671+0000] {standard_task_runner.py:88} INFO - Job 305: Subtask retried_task
[2024-04-09T17:09:43.955+0000] {task_command.py:423} INFO - Running <TaskInstance: task_states_demo.retried_task scheduled__2023-10-05T00:00:00+00:00 [running]> on host fe7355ff6de5
[2024-04-09T17:09:44.101+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_states_demo' AIRFLOW_CTX_TASK_ID='retried_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-05T00:00:00+00:00'
[2024-04-09T17:09:44.114+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T17:09:44.115+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-04-09T17:09:44.131+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T17:09:44.151+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-09T17:09:44.177+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-09T17:09:44.190+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=task_states_demo, task_id=retried_task, execution_date=20231005T000000, start_date=20240409T170943, end_date=20240409T170944
[2024-04-09T17:09:44.213+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 305 for task retried_task (Bash command failed. The command returned a non-zero exit code 1.; 1814)
[2024-04-09T17:09:44.235+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T17:09:44.277+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
