[2024-04-09T16:53:10.309+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2024-04-09T16:53:10.312+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_states_demo.retried_task scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2024-04-09T16:53:10.312+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-09T16:53:10.317+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): retried_task> on 2023-08-15 00:00:00+00:00
[2024-04-09T16:53:10.321+0000] {standard_task_runner.py:60} INFO - Started process 667 to run task
[2024-04-09T16:53:10.323+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task_states_demo', 'retried_task', 'scheduled__2023-08-15T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/task_states_demo.py', '--cfg-path', '/tmp/tmplonl1mh1']
[2024-04-09T16:53:10.324+0000] {standard_task_runner.py:88} INFO - Job 85: Subtask retried_task
[2024-04-09T16:53:10.353+0000] {task_command.py:423} INFO - Running <TaskInstance: task_states_demo.retried_task scheduled__2023-08-15T00:00:00+00:00 [running]> on host fe7355ff6de5
[2024-04-09T16:53:10.379+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_states_demo' AIRFLOW_CTX_TASK_ID='retried_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-15T00:00:00+00:00'
[2024-04-09T16:53:10.380+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T16:53:10.381+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-04-09T16:53:10.386+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T16:53:10.387+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-09T16:53:10.392+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-09T16:53:10.393+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=task_states_demo, task_id=retried_task, execution_date=20230815T000000, start_date=20240409T165310, end_date=20240409T165310
[2024-04-09T16:53:10.398+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task retried_task (Bash command failed. The command returned a non-zero exit code 1.; 667)
[2024-04-09T16:53:10.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T16:53:10.428+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
